apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-2
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-3
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "150m"
        memory: "192Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-4
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "300m"
        memory: "512Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-5
  labels:
    app: test-app
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        cpu: "50m"
        memory: "64Mi"
